version: '3.8'

services:
  frontend:
    container_name: frontend-docker
    build:
      context: frontend
      dockerfile: front.dev.Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

  backend:
    container_name: backend-docker
    restart: always
    build:
      context: backend
      dockerfile: back.dev.Dockerfile
    expose:
      - 55000
    ports:
      - 55000:55000
    volumes:
      - ./backend:/www
    links:
      - db
    depends_on:
      - frontend

  db:
    image: mysql:5.7
    container_name: my-back-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qwerqwer123"
      MYSQL_DATABASE: "fullstack_test"
      MYSQL_USER: "wool"
      MYSQL_PASSWORD: "qwerqwer123"
    volumes:
      - ./mysql-data:/var/lib/mysql


