version: '3.8'

services:
  frontend:
    container_name: linechart-frontend-docker
    build:
      context: frontend
      dockerfile: front.dev.Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

  backend:
    container_name: linechart-backend-docker
    restart: always
    build:
      context: backend
      dockerfile: back.dev.Dockerfile
    expose:
      - 5050
    ports:
      - 5050:5500
    volumes:
      - ./backend:/www
    depends_on:
      - frontend


